# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be510fcaa1e5683cd4be5a63ac71f9c8db93c87e2caabcc7f475223291c63d1915f1a0e5634a7ba229e9e74a728d00a0aae6e40d04bb3e1914c0e7536ccf690

test:
  secret_key_base: 74bcdd5dbcc0ad043bc435ec8a06491c065590fec64a1d2ce8873b706c6960aa7d328f531d5a668e6146bc378de7510643c4c732576fb73dca0046aa98bdf436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
